[project]
name = "repl-nix-videoactionclassifier"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "av>=14.0.0",
    "numpy>=2.1.3",
    "streamlit>=1.40.2",
    "torch>=2.5.1",
    "transformers>=4.46.3",
]
